/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lyman_oldusendkdemo_MainActivity */

#ifndef _Included_com_lyman_oldusendkdemo_MainActivity
#define _Included_com_lyman_oldusendkdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lyman_oldusendkdemo_MainActivity
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lyman_oldusendkdemo_MainActivity_getName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
